# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmodel.proto\x12 gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB\"e\n\rIrisDataFrame\x12\x14\n\x0csepal_length\x18\x01 \x03(\x01\x12\x13\n\x0bsepal_width\x18\x02 \x03(\x01\x12\x14\n\x0cpetal_length\x18\x03 \x03(\x01\x12\x13\n\x0bpetal_width\x18\x04 \x03(\x01\"\x1c\n\x0b\x43lassifyOut\x12\r\n\x05value\x18\x01 \x03(\x03\x32s\n\x05Model\x12j\n\x08\x63lassify\x12/.gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame\x1a-.gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.ClassifyOutb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IRISDATAFRAME = _descriptor.Descriptor(
  name='IrisDataFrame',
  full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame.sepal_length', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame.sepal_width', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame.petal_length', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame.petal_width', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=150,
)


_CLASSIFYOUT = _descriptor.Descriptor(
  name='ClassifyOut',
  full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.ClassifyOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.ClassifyOut.value', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['IrisDataFrame'] = _IRISDATAFRAME
DESCRIPTOR.message_types_by_name['ClassifyOut'] = _CLASSIFYOUT

IrisDataFrame = _reflection.GeneratedProtocolMessageType('IrisDataFrame', (_message.Message,), dict(
  DESCRIPTOR = _IRISDATAFRAME,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.IrisDataFrame)
  ))
_sym_db.RegisterMessage(IrisDataFrame)

ClassifyOut = _reflection.GeneratedProtocolMessageType('ClassifyOut', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYOUT,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:gppCIxXIQXOogdcyEAIoJkiwjTjjsTrB.ClassifyOut)
  ))
_sym_db.RegisterMessage(ClassifyOut)


# @@protoc_insertion_point(module_scope)
